env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  semi: [2, "never"],
  quotes: ["off", "single"],
  linebreak-style: 0
}
