name: Check the Python source code in the engine
on: [push]
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: pip install -r requirements.txt
    - name: Run PyLint
      run: pylint engine/*.py
